"""initial_schema

Revision ID: 394e2f71958e
Revises: 
Create Date: 2026-07-10 02:33:33.679914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '394e2f71958e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_path', sa.String(length=255), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_name'), 'cast', ['name'], unique=False)
    op.create_index(op.f('ix_cast_tmdb_id'), 'cast', ['tmdb_id'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_genres_tmdb_id'), 'genres', ['tmdb_id'], unique=True)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_name'), 'keywords', ['name'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_content_type'), 'media', ['content_type'], unique=False)
    op.create_table('search_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_clicked_id', sa.Integer(), nullable=True),
    sa.Column('stream_clicked', sa.Boolean(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_sessions_session_token'), 'search_sessions', ['session_token'], unique=False)
    op.create_table('media_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_asset_media_type', 'media_asset', ['media_id', 'asset_type'], unique=False)
    op.create_index('idx_media_asset_primary', 'media_asset', ['media_id', 'asset_type', 'is_primary'], unique=False)
    op.create_index(op.f('ix_media_asset_media_id'), 'media_asset', ['media_id'], unique=False)
    op.create_table('media_cast',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('cast_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cast_id'], ['cast.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'cast_id')
    )
    op.create_table('media_embedding',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('needs_rebuild', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_index('idx_media_embedding_hnsw', 'media_embedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_table('media_enrichment',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('narrative_dna', sa.Text(), nullable=True),
    sa.Column('themes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tone_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('darkness_score', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('energy_score', sa.Integer(), nullable=True),
    sa.Column('mood_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('craving_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_fully_scored', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_index(op.f('ix_media_enrichment_is_fully_scored'), 'media_enrichment', ['is_fully_scored'], unique=False)
    op.create_table('media_genres',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.create_table('media_keywords',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'keyword_id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=False),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('belongs_to_collection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('production_countries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('spoken_languages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('origin_country', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('production_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('streaming_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movies_adult_popularity', 'movies', ['adult', 'popularity'], unique=False)
    op.create_index('idx_movies_language_popularity', 'movies', ['original_language', 'popularity'], unique=False)
    op.create_index('idx_movies_release_rating', 'movies', ['release_date', 'vote_average'], unique=False)
    op.create_index('idx_movies_updated_at', 'movies', ['updated_at'], unique=False)
    op.create_index(op.f('ix_movies_adult'), 'movies', ['adult'], unique=False)
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_movies_media_id'), 'movies', ['media_id'], unique=True)
    op.create_index(op.f('ix_movies_original_language'), 'movies', ['original_language'], unique=False)
    op.create_index(op.f('ix_movies_popularity'), 'movies', ['popularity'], unique=False)
    op.create_index(op.f('ix_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_movies_vote_average'), 'movies', ['vote_average'], unique=False)
    op.create_index('uq_movies_tmdb_id', 'movies', ['tmdb_id'], unique=True)
    op.create_table('sixty_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('craving', sa.String(length=50), nullable=True),
    sa.Column('film_picked_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('seconds_taken', sa.Integer(), nullable=True),
    sa.Column('watch_clicked', sa.Boolean(), nullable=True),
    sa.Column('share_clicked', sa.Boolean(), nullable=True),
    sa.Column('retry_clicked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['film_picked_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sixty_sessions_session_token'), 'sixty_sessions', ['session_token'], unique=False)
    op.create_table('tv_shows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('number_of_episodes', sa.Integer(), nullable=True),
    sa.Column('episode_run_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_air_date', sa.DateTime(), nullable=True),
    sa.Column('in_production', sa.Boolean(), nullable=True),
    sa.Column('networks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('show_type', sa.String(length=50), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=False),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('belongs_to_collection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('production_countries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('spoken_languages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('origin_country', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('production_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('streaming_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tv_shows_adult_popularity', 'tv_shows', ['adult', 'popularity'], unique=False)
    op.create_index('idx_tv_shows_language_popularity', 'tv_shows', ['original_language', 'popularity'], unique=False)
    op.create_index('idx_tv_shows_release_rating', 'tv_shows', ['release_date', 'vote_average'], unique=False)
    op.create_index('idx_tv_shows_updated_at', 'tv_shows', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tv_shows_adult'), 'tv_shows', ['adult'], unique=False)
    op.create_index(op.f('ix_tv_shows_imdb_id'), 'tv_shows', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_tv_shows_media_id'), 'tv_shows', ['media_id'], unique=True)
    op.create_index(op.f('ix_tv_shows_original_language'), 'tv_shows', ['original_language'], unique=False)
    op.create_index(op.f('ix_tv_shows_popularity'), 'tv_shows', ['popularity'], unique=False)
    op.create_index(op.f('ix_tv_shows_release_date'), 'tv_shows', ['release_date'], unique=False)
    op.create_index(op.f('ix_tv_shows_title'), 'tv_shows', ['title'], unique=False)
    op.create_index(op.f('ix_tv_shows_tmdb_id'), 'tv_shows', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_tv_shows_vote_average'), 'tv_shows', ['vote_average'], unique=False)
    op.create_index('uq_tv_shows_tmdb_id', 'tv_shows', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tv_shows_tmdb_id', table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_vote_average'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_tmdb_id'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_title'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_release_date'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_popularity'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_original_language'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_media_id'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_imdb_id'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_adult'), table_name='tv_shows')
    op.drop_index('idx_tv_shows_updated_at', table_name='tv_shows')
    op.drop_index('idx_tv_shows_release_rating', table_name='tv_shows')
    op.drop_index('idx_tv_shows_language_popularity', table_name='tv_shows')
    op.drop_index('idx_tv_shows_adult_popularity', table_name='tv_shows')
    op.drop_table('tv_shows')
    op.drop_index(op.f('ix_sixty_sessions_session_token'), table_name='sixty_sessions')
    op.drop_table('sixty_sessions')
    op.drop_index('uq_movies_tmdb_id', table_name='movies')
    op.drop_index(op.f('ix_movies_vote_average'), table_name='movies')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_release_date'), table_name='movies')
    op.drop_index(op.f('ix_movies_popularity'), table_name='movies')
    op.drop_index(op.f('ix_movies_original_language'), table_name='movies')
    op.drop_index(op.f('ix_movies_media_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_adult'), table_name='movies')
    op.drop_index('idx_movies_updated_at', table_name='movies')
    op.drop_index('idx_movies_release_rating', table_name='movies')
    op.drop_index('idx_movies_language_popularity', table_name='movies')
    op.drop_index('idx_movies_adult_popularity', table_name='movies')
    op.drop_table('movies')
    op.drop_table('media_keywords')
    op.drop_table('media_genres')
    op.drop_index(op.f('ix_media_enrichment_is_fully_scored'), table_name='media_enrichment')
    op.drop_table('media_enrichment')
    op.drop_index('idx_media_embedding_hnsw', table_name='media_embedding', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('media_embedding')
    op.drop_table('media_cast')
    op.drop_index(op.f('ix_media_asset_media_id'), table_name='media_asset')
    op.drop_index('idx_media_asset_primary', table_name='media_asset')
    op.drop_index('idx_media_asset_media_type', table_name='media_asset')
    op.drop_table('media_asset')
    op.drop_index(op.f('ix_search_sessions_session_token'), table_name='search_sessions')
    op.drop_table('search_sessions')
    op.drop_index(op.f('ix_media_content_type'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_keywords_name'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_genres_tmdb_id'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_cast_tmdb_id'), table_name='cast')
    op.drop_index(op.f('ix_cast_name'), table_name='cast')
    op.drop_table('cast')
    # ### end Alembic commands ###
